var allFoods = [
  {
    id: 1,
    name: "Fried Chicken Bento",
    description: "This is Fried chicken bento",
    price: 9.99,
    photo: "https://i.imgur.com/fWhgOnj.png",
    category: "lunch",
  },
  {
    id: 2,
    name: "Tarragon-Rubbed-Salmon",
    description: "This is Tarragon-Rubbed-Salmon",
    price: 6.99,
    photo: "https://i.imgur.com/CKY81P9.png",
    category: "lunch",
  },
  {
    id: 3,
    name: "Indian Lunch",
    description: "This is Indian Lunch",
    price: 8.99,
    photo: "https://i.imgur.com/2hzf2Lt.png",
    category: "lunch",
  },
  {
    id: 4,
    name: "Best Stoak",
    description: "This is Best Stoak",
    price: 15.99,
    photo: "https://i.imgur.com/C8Uknuk.png",
    category: "lunch",
  },
  {
    id: 5,
    name: "Bangladeshi Meal",
    description: "This is Tarragon-Rubbed-Salmon",
    price: 30.99,
    photo: "https://i.imgur.com/qYtLWrz.png",
    category: "lunch",
  },
  {
    id: 6,
    name: "Bagel and cream cheese",
    description: "This is Bagel and cream cheese",
    price: 6.99,
    photo: "https://i.imgur.com/p9ulz9K.png",
    category: "breakfast",
  },
  {
    id: 7,
    name: "Breakfast Sandwich",
    description: "This is Breakfast Sandwich",
    price: 9.99,
    photo: "https://i.imgur.com/PXo8lpu.png",
    category: "breakfast",
  },
  {
    id: 8,
    name: "Backed Chicken",
    description: "This is Backed Chicken",
    price: 10.99,
    photo: "https://i.imgur.com/cWJBqxn.png",
    category: "breakfast",
  },
  {
    id: 9,
    name: "Eggs Benedict",
    description: "This is Eggs Benedict",
    price: 8.99,
    photo: "https://i.imgur.com/k98acKS.png",
    category: "breakfast",
  },
  {
    id: 10,
    name: "Toast Croissant Fried egg",
    description: "This is Toast Croissant Fried egg",
    price: 19.99,
    photo: "https://i.imgur.com/yJIYQxk.png",
    category: "breakfast",
  },
  {
    id: 11,
    name: "Full Breakfast Fried Egg toast",
    description: "This is Healthy",
    price: 3.99,
    photo: "https://i.imgur.com/ANlJ2KE.png",
    category: "breakfast",
  },
  {
    id: 12,
    name: "Salmon with grapefruit",
    description: "This is Healthy",
    price: 9.99,
    photo: "https://i.imgur.com/owkOG3B.png",
    category: "dinner",
  },
  {
    id: 13,
    name: "Lemony Salmon Piccata",
    description: "This is Healthy",
    price: 10.99,
    photo: "https://i.imgur.com/zMqqPoE.png",
    category: "dinner",
  },
  {
    id: 14,
    name: "Pork Tenderion With Quinoa",
    description: "This is Healthy",
    price: 12.99,
    photo: "https://i.imgur.com/dFWLuVu.png",
    category: "dinner",
  },
  {
    id: 15,
    name: "French fries with cheese",
    description: "This is Healthy",
    price: 8.99,
    photo: "https://i.imgur.com/JmGvd99.png",
    category: "dinner",
  },
  {
    id: 16,
    name: "Gurlic Butter Backed Salmon",
    description: "This is Healthy",
    price: 6.99,
    photo: "https://i.imgur.com/ILsFBHZ.png",
    category: "dinner",
  },
  {
    id: 17,
    name: "Backed Chicken",
    description: "This is Healthy",
    price: 9.99,
    photo: "https://i.imgur.com/FU37QNi.png",
    category: "dinner",
  },
  {
    id: 18,
    name: "Chicken Biriyani",
    description: "This is Fried chicken biriyani",
    price: 22.99,
    photo: "https://i.imgur.com/R1aLpkY.png",
    category: "lunch",
  },
];

export default allFoods;
