var allFoods = [
  {
    id: 1,
    name: "Fried Chicken Bento",
    description: "This is Fried chicken bento",
    price: 9.99,
    photo: "/images/lunch/lunch2.png",
    category: "lunch",
  },
  {
    id: 2,
    name: "Tarragon-Rubbed-Salmon",
    description: "This is Tarragon-Rubbed-Salmon",
    price: 6.99,
    photo: "/images/lunch/lunch3.png",
    category: "lunch",
  },
  {
    id: 3,
    name: "Indian Lunch",
    description: "This is Indian Lunch",
    price: 8.99,
    photo: "/images/lunch/lunch4.png",
    category: "lunch",
  },
  {
    id: 4,
    name: "Best Stoak",
    description: "This is Best Stoak",
    price: 15.99,
    photo: "/images/lunch/lunch5.png",
    category: "lunch",
  },
  {
    id: 5,
    name: "Bangladeshi Meal",
    description: "This is Tarragon-Rubbed-Salmon",
    price: 30.99,
    photo: "/images/lunch/lunch6.png",
    category: "lunch",
  },
  {
    id: 6,
    name: "Bagel and cream cheese",
    description: "This is Bagel and cream cheese",
    price: 6.99,
    photo: "/images/Breakfast/breakfast1.png",
    category: "breakfast",
  },
  {
    id: 7,
    name: "Breakfast Sandwich",
    description: "This is Breakfast Sandwich",
    price: 9.99,
    photo: "/images/Breakfast/breakfast2.png",
    category: "breakfast",
  },
  {
    id: 8,
    name: "Backed Chicken",
    description: "This is Backed Chicken",
    price: 10.99,
    photo: "/images/Breakfast/breakfast3.png",
    category: "breakfast",
  },
  {
    id: 9,
    name: "Eggs Benedict",
    description: "This is Eggs Benedict",
    price: 8.99,
    photo: "/images/Breakfast/breakfast4.png",
    category: "breakfast",
  },
  {
    id: 10,
    name: "Toast Croissant Fried egg",
    description: "This is Toast Croissant Fried egg",
    price: 19.99,
    photo: "/images/Breakfast/breakfast5.png",
    category: "breakfast",
  },
  {
    id: 11,
    name: "Full Breakfast Fried Egg toast",
    description: "This is Healthy",
    price: 3.99,
    photo: "/images/Breakfast/breakfast6.png",
    category: "breakfast",
  },
  {
    id: 12,
    name: "Salmon with grapefruit",
    description: "This is Healthy",
    price: 9.99,
    photo: "/images/Dinner/dinner1.png",
    category: "dinner",
  },
  {
    id: 13,
    name: "Lemony Salmon Piccata",
    description: "This is Healthy",
    price: 10.99,
    photo: "/images/Dinner/dinner2.png",
    category: "dinner",
  },
  {
    id: 14,
    name: "Pork Tenderion With Quinoa",
    description: "This is Healthy",
    price: 12.99,
    photo: "/images/Dinner/dinner3.png",
    category: "dinner",
  },
  {
    id: 15,
    name: "French fries with cheese",
    description: "This is Healthy",
    price: 8.99,
    photo: "/images/Dinner/dinner4.png",
    category: "dinner",
  },
  {
    id: 16,
    name: "Gurlic Butter Backed Salmon",
    description: "This is Healthy",
    price: 6.99,
    photo: "/images/Dinner/dinner5.png",
    category: "dinner",
  },
  {
    id: 17,
    name: "Backed Chicken",
    description: "This is Healthy",
    price: 9.99,
    photo: "/images/Dinner/dinner6.png",
    category: "dinner",
  },
  {
    id: 18,
    name: "Chicken Biriyani",
    description: "This is Fried chicken biriyani",
    price: 22.99,
    photo: "/images/lunch/lunch1.png",
    category: "lunch",
  },
];

export default allFoods;
